### ISSUE TITLE
Change 'python -m bentham' to run twistd daemon

### ISSUE THREAD

**Issue by kotfic** [danlamanna/bentham#2]
Currently `python -m bentham` runs the CherryPy app.  This should be moved into the `clients/` folder and the main entry point should load/run a twistd  daemon

**Comment by danlamanna** [comment]
Maybe we should look at how to set this up in a larger context (with systemd). For example how are trackers started and how are individual clients started, and what does "bentham" do.

I think something like `bentham tracker` to start the tracker makes sense, and `bentham client web` to run different clients.

**Comment by kotfic** [comment]
Design has changed - we're going to use celery to manage schedule of events,  I am closing this
