### ISSUE TITLE
Settle on a database schema

### ISSUE THREAD

**Issue by danlamanna** [danlamanna/bentham#3]
Right now [this](https://github.com/danlamanna/bentham/blob/df88e582f84d4a319cd94fa9309643b4fc40e53b/api/database.py#L14-L22) is the schema. Is this good enough for a rough draft?

**Comment by kotfic** [comment]
Should messages have source identifiers (i.e. what tracker/configuration pair)? 
Equally should we have daemon identifiers (i.e.  what machine?).

**Comment by danlamanna** [comment]
Source identifiers: definitely - [this](https://github.com/danlamanna/bentham/blob/df88e582f84d4a319cd94fa9309643b4fc40e53b/trackers/events.py#L14) never got entered into the database but should have. It needs to be trivial to say "show me all events that occurred on one github account".

Daemon identifiers: I don't know that this matters for storage purposes. Who cares if the tweet was retrieved by a server or a laptop? The only benefit I could see it providing is a debugging one, and I think tracker-side logging can take care of that in a short lived manner.
